### PR TITLE
Add information about swd flashing (pin layout etc.)

### PR DESCRIPTION
**Pull request by alex-nitrokey**

### CODE REVIEW

**Comment by alex-nitrokey** [comment]
> Please make the text non-redundant to this description and refer to each other texts accordingly.

Yes, funnily I found these instructions myself a day after and planned to merge it today :smile:

**Comment by alex-nitrokey** [comment]
Ready for review :wink:

**Comment by jans23** [comment]
Looks good to me. @szszszsz anything to add?

**Comment by szszszsz** [comment]
Looks right!

**Comment by szszszsz** [comment]
Merged!
Suggestion: let's keep images in a separate folder (done that already).

**Pull request merged**
