### PR TITLE
HSM: Remove HID interface from device descriptor and change Name

### PR DESCRIPTION
**Pull request by MaVo159**
Can we make this a new branch instead of applying to master? That would make life a bit easier when working on the Pro stuff.

### CODE REVIEW

**Comment by szszszsz** [comment]
Hi @MaVo159, 
Sure! I have created `hsm` branch in repo (where I have already included your commit). Please make future PRs against it.

**Comment by MaVo159** [comment]
Ok. I see you also fixed the interface number (on my side the OS didn't seem to care about it). Could you also change the device Id to whatever the HSM uses?, Then I don't have to send another pull request.

**Comment by szszszsz** [comment]
Do you mean default PID? Indeed this might be helpful. In the meantime you can use:
`make PID=0x4230`

**Comment by MaVo159** [comment]
Yes that is what I meant. Thanks.

**Pull request closed without merging**
